version: "2"
services:
  spring_batch_db:
    container_name: new_arrival_batch
    image: mariadb:10.4
    restart: always
    ports:
      - "33307:3306"
    volumes:
      - ~/docker-repo/new_arrival_batch:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=spring_batch
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    command: mysqld --character-set-server=utf8mb4

